
export type MacroType = 'carboidrati' | 'proteine' | 'grassi';

export interface MacroValue {
  kcal: number;
  grammi: number;
}

export interface MacroSplit {
  carboidrati: MacroValue;
  proteine: MacroValue;
  grassi: MacroValue;
}

export interface SettimanaConfig {
  numero: number;
  giorniON: {
    calorieTotal: number;
    macros: MacroSplit;
  };
  giorniOFF: {
    calorieTotal: number;
    macros: MacroSplit;
  };
}

export type TipologiaGiornata = 
  | 'ON_4_PASTI_WOD_SERA'
  | 'ON_4_PASTI_WOD_MATTINA'
  | 'ON_5_PASTI_WOD_MATTINA'
  | 'ON_5_PASTI_WOD_SERA'
  | 'OFF_4_PASTI'
  | 'OFF_4_PASTI_CARBS'
  | 'OFF_5_PASTI';

export type NomePasto = 'colazione' | 'spuntino' | 'pranzo' | 'merenda' | 'cena';

export interface DistribuzionePasto {
  pasto: NomePasto;
  percentuali: {
    carboidrati: number;
    proteine: number;
    grassi: number;
  };
}

export interface TipologiaGiornataConfig {
  tipo: TipologiaGiornata;
  label: string;
  categoria: 'ON' | 'OFF';
  numeroPasti: 4 | 5;
  distribuzioni: DistribuzionePasto[];
}

export type AlimentoCategoria = 'Pesce' | 'Carne Rossa' | 'Carne Bianca' | 'Carbo' | 'Grassi/Pro';

export interface Alimento {
  id: string;
  nome: string;
  per100g: {
    carboidrati: number;
    proteine: number;
    grassi: number;
    kcal: number;
  };
  /** Categoria alimentare per il generatore settimanale */
  categoria?: AlimentoCategoria;
  /** true = creato dall'utente (edit/delete consentiti); assente/false = certificato AB (solo lettura) */
  isCustom?: boolean;
}

export interface AlimentoSelezionato {
  alimentoId: string;
  quantita: number; // grams
}

export type PastoStatus = 'regular' | 'skipped' | 'cheat';

export interface PastoComposto {
  id: string;
  data: string; // YYYY-MM-DD
  settimana: number;
  tipologiaGiornata: TipologiaGiornata;
  nomePasto: NomePasto;
  alimenti: AlimentoSelezionato[];
  status: PastoStatus;
  /** true = pasto generato automaticamente (icona "A" in UI) */
  isAutoGenerated?: boolean;
}

export interface DailySetup {
  date: string; // YYYY-MM-DD
  settimana: number;
  tipologiaGiornata: TipologiaGiornata;
}

/** Preferenze modalità FACILE: usate per generare piano semplificato */
export interface FacileSetupPreferences {
  /** Calorie giorni allenamento (ON) */
  kcal_on: number;
  /** Calorie giorni riposo (OFF) */
  kcal_off: number;
  /** @deprecated usare kcal_on/kcal_off - mantenuto per retrocompatibilità */
  targetCalories?: number;
  mealFrequency: 4 | 5;
  trainingTiming: 'morning' | 'afternoon';
  /** Giorni ON: 0=Domenica, 1=Lunedì, ..., 6=Sabato (subset di 0-6) */
  onDays: number[];
}

/** Target per singolo pasto (output motore calcolo Facile) */
export interface EasyModeMealTarget {
  kcal: number;
  carboidrati: number;
  proteine: number;
  grassi: number;
}

/** Profili ON/OFF per modalità Facile */
export interface EasyModeTargets {
  ON: Partial<Record<NomePasto, EasyModeMealTarget>>;
  OFF: Partial<Record<NomePasto, EasyModeMealTarget>>;
}

export type SetupMode = 'pro' | 'facile';

/** Override manuale stato giorno per data (YYYY-MM-DD -> ON | OFF). Persiste per la giornata. */
export type ManualDayTypeOverrides = Record<string, 'ON' | 'OFF'>;

export interface AppState {
  isConfigured: boolean;
  setupMode?: SetupMode;
  facilePreferences?: FacileSetupPreferences;
  easy_mode_targets?: EasyModeTargets;
  /** In modalità Facile: override manuale ON/OFF per data */
  manualDayTypeOverrides?: ManualDayTypeOverrides;
  settimane: SettimanaConfig[];
  tipologie: TipologiaGiornataConfig[];
  alimenti: Alimento[];
  pastiSalvati: PastoComposto[];
  dailySetups: DailySetup[]; // Memorizza quale settimana/tipo è stata scelta per ogni giorno
}
